spring.application.name=prices

# Datasource H2 creado en memoria
# -1 para mentener viva la BD y que no se cierre
spring.datasource.url=jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1

# Consola web
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=create-drop

#Hibernate cerrar sesión y no la mantenemos abierta durante toda la petición
spring.jpa.open-in-view=false

#No sé si es necesario, comprobar antes de enviar. Pero parece que con la nueva modularización de la 4.x, a veces se necesita la propiedad para forzar que se ejecute siempre data.sql
spring.jpa.defer-datasource-initialization=true